### ISSUE TITLE
[Question] Permission denied for Installation

### ISSUE THREAD

**Issue by Xwoder** [thingsboard/thingsboard-edge#23]
**Component**

 * Installation

**Description**
Error Message
```
Error response from daemon: error while creating mount source path '/host_mnt/home/shft/.mytb-edge-data/db': mkdir /host_mnt/home/shft/.mytb-edge-data/db: permission denied
```

Command in terminal
```bash
sudo rm -rf ~/.mytb-edge-data/
sudo rm -rf ~/.mytb-edge-logs/

mkdir -p ~/.mytb-edge-data && sudo chown -R 799:799 ~/.mytb-edge-data
mkdir -p ~/.mytb-edge-logs && sudo chown -R 799:799 ~/.mytb-edge-logs
```

docker-compose-edge.yml
```yml
version: '2.2'
services:
  mytbedge:
    restart: always
    image: "thingsboard/tb-edge:3.4.1EDGE"
    ports:
      - "18080:8080"
      - "11883:1883"
      - "15683-15688:5683-5688/udp"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/tb-edge
      CLOUD_ROUTING_KEY: PUT_YOUR_EDGE_KEY_HERE # e.g. 19ea7ee8-5e6d-e642-4f32-05440a529015
      CLOUD_ROUTING_SECRET: PUT_YOUR_EDGE_SECRET_HERE # e.g. bztvkvfqsye7omv9uxlp
      CLOUD_RPC_HOST: PUT_YOUR_CLOUD_IP # e.g. 192.168.1.250 or demo.thingsboard.io
    volumes:
      - ~/.mytb-edge-data:/data
      - ~/.mytb-edge-logs:/var/log/tb-edge
  postgres:
    restart: always
    image: "postgres:12"
    ports:
      - "5432"
    environment:
      POSTGRES_DB: tb-edge
      POSTGRES_PASSWORD: postgres
    volumes:
      - ~/.mytb-edge-data/db:/var/lib/postgresql/data
```

**Environment**

 * OS:  Ubuntu 22.04.1 LTS
 * ThingsBoard: 3.4.1
 * Browser: Microsoft Edge
