### ISSUE TITLE
Data was sent from ThingsBoard Gateway but Device is still in inactive mode on ThingsBoard Edge server

### ISSUE THREAD

**Issue by ktran1005** [thingsboard/thingsboard-edge#96]
**Component**

 * Generic

**Description**
Hello ThingsBoard Edge team, I am implementing a custom connector that can connect to ThingsBoard Gateway and the gateway will send the data to the edge and from the edge to the cloud. I was able to implement a customer connector that can connect to the gateway and they gateway can send the data to the ThingsBoard server directly. I can see the real-time data in the latest telemetry section on ThingsBoard cloud. However, when I tried to send the data to the edge, it seemed like the edge could not receive the data and kept being in inactive mode. I am currently running the edge as a docker container (localhost:8080). I wonder if you guys have any suggestion to fix this issue?hg

docker-compose.yml
```yaml
version: '3.8'
services:
  mytbedge:
    restart: always
    image: "thingsboard/tb-edge:3.6.2EDGE"
    ports:
      - "8080:8080"
      - "1883:1883"
      - "5683-5688:5683-5688/udp"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/tb-edge
      CLOUD_ROUTING_KEY: 
      CLOUD_ROUTING_SECRET: 
      CLOUD_RPC_HOST: demo.thingsboard.io
    volumes:
      - tb-edge-data:/data
      - tb-edge-logs:/var/log/tb-edge
  postgres:
    restart: always
    image: "postgres:15"
    ports:
      - "5432"
    environment:
      POSTGRES_DB: tb-edge
      POSTGRES_PASSWORD: postgres
    volumes:
      - tb-edge-postgres-data:/var/lib/postgresql/data

volumes:
  tb-edge-data:
    name: tb-edge-data
  tb-edge-logs:
    name: tb-edge-logs
  tb-edge-postgres-data:
    name: tb-edge-postgres-data
```

log of Edge:
![image](https://github.com/thingsboard/thingsboard-edge/assets/88155108/04d21d5f-533a-4ecd-8c9e-75831989428a)

log of GW:
service.log
![Screenshot from 2024-02-09 09-37-31](https://github.com/thingsboard/thingsboard-edge/assets/88155108/97df5965-060a-4497-80b2-0b97d4ee6198)

connector.log
![Screenshot from 2024-02-09 09-38-36](https://github.com/thingsboard/thingsboard-edge/assets/88155108/73b5f319-f4e5-44d9-a090-bfbec9def803)

converter.log
![Screenshot from 2024-02-09 09-39-28](https://github.com/thingsboard/thingsboard-edge/assets/88155108/5f55fe54-c96d-4864-94df-eca04195f8dd)

**Environment**

 * OS:  Ubuntu 18.04.6
 * ThingsBoard: 3.6
